### ISSUE TITLE
Progress Tracker: NextJS Rewrite

### ISSUE THREAD

**Issue by null2264** [ZiRO-Bot/frontend#1]
From my experience, VueJS is a bit painful to work with since it's completely different from what I'm used to (Android and iOS app development). NextJS (or React in general) seems to be closest to the Android/iOS app development workflow, so I decided to rewrite the project from Vue to NextJS.

- [x] Auth
   - [x] Login (from new tab/window)
   - [ ] Logout
- [x] Dashboard
   - [x] Guild List (only show "managed by user" guilds)
   - [ ] Guild frontpage
   - [x] Guild Meta Settings
     - [x] Manage Prefix
- [x] Meta
   - [ ] WebSocket
      - [ ] Guild Update
      - [ ] User Update
   - [x] NavBar
      - [x] Guild Dashboard NavBar
      - [x] Homepage NavBar
